version: "3.8"

services:
  backend:
    build:
      context: ./backend 
    container_name: fastapi-backend
    ports:
      - "8000:8000"  

  frontend:
    build:
      context: ./frontend 
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000 
