HAMBURG_GEOJSON_PATH = 'sentinel5plib/geojson/hamburg_map.geojson'
DEFAULT_AVERAGE_YEAR_VALUE = 2025
DEFAULT_AVERAGE_WEEK_VALUE = 2
DEFAULT_AVERAGE_MONTH_VALUE = 1
DEFAULT_MAP_RASTER_OUTPUT_PATH = 'sentinel5plib/maps/raster_map.tif' 
DEFAULT_MAP_VECTOR_OUTPUT_PATH = 'sentinel5plib/maps/vector_map.geojson'
DEFAULT_MAP_DATA_START_DATE = '2025-01-01'
DEFAULT_MAP_DATA_END_DATE = '2025-12-31'
   
